apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radiopulse
resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - web.yaml
  - worker.yaml
  - ingress.yaml
