apiVersion: v1
kind: Secret
metadata:
  name: radiopulse-secrets
  namespace: radiopulse
type: Opaque
stringData:
  postgres-password: postgres
  api-auth-key: radiopulse-dev-signing-key-please-change
  conn-radiopulsedb: Host=postgres;Port=5432;Database=radiopulsedb;Username=postgres;Password=postgres
