apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: radiopulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/OWNER/radiopulse-worker:latest
          env:
            - name: ConnectionStrings__radiopulsedb
              valueFrom:
                secretKeyRef:
                  name: radiopulse-secrets
                  key: conn-radiopulsedb
            - name: ConnectionStrings__redis
              value: redis:6379
            - name: UseAzureAi
              value: "false"
            - name: EnableHttpsRedirection
              value: "false"
